In [22]:
#import de tous les 
from base import *

In [28]:
df = {}

In [46]:
import pyspark.sql.functions as f

for x in range (1,6):
    df[x] = reviews.where(reviews.review_score == x).selectExpr("review_comment_message as message").dropna()
    df[x] = df[x].withColumn("Longueur",length(col("message"))) #longueur du message
    print ("note: "+str(x)+": ")
    #enlever les stop words
    df[x] = df[x].withColumn("mots",f.explode(f.split(f.col("message"),' '))).groupBy("mots").count().sort('count', ascending=False).show()
    #df[x].agg(avg(col("Longueur"))).show() #moyenne du nb de mots
    #On voit que plus les utilisateurs mettent une mauvaise notes, plus longs sont leurs messages (car ils sont énervés)
    #Compter le top nb de mots

note: 1:
+-------+-----+
|   mots|count|
+-------+-----+
|      o| 5776|
|      e| 4980|
|    não| 4620|
|     de| 3785|
|produto| 3494|
|      a| 3393|
|    que| 3003|
| recebi| 2158|
|       | 1970|
|     do| 1851|
|    com| 1758|
|     um| 1666|
|    foi| 1478|
|     no| 1282|
|      O| 1227|
|    Não| 1208|
|   para| 1206|
|     da| 1158|
|    uma| 1093|
|      é| 1014|
+-------+-----+
only showing top 20 rows

note: 2:
+-------+-----+
|   mots|count|
+-------+-----+
|      o| 1248|
|      e| 1006|
|      a|  931|
|    não|  922|
|     de|  870|
|produto|  787|
|    que|  735|
|     do|  520|
|       |  460|
|    com|  443|
|     um|  383|
|   veio|  366|
| recebi|  355|
|      O|  339|
|      é|  328|
|     no|  323|
|    foi|  316|
|   para|  308|
|     na|  297|
|     da|  285|
+-------+-----+
only showing top 20 rows

note: 3:
+-------+-----+
|   mots|count|
+-------+-----+
|      o| 1767|
|      a| 1267|
|      e| 1229|
|    que| 1162|
|     de| 1134|
|    não| 1094|
|produto| 1068|
|     do|  879|
|       |  772|
|    com|  602|
|      é|  592|
|     um|  553|
|      O|  523|
|     no|  510|
|    mas|  467|
|   veio|  461|
|    foi|  439|
|     da|  417|
|     na|  403|
|  muito|  402|
+-------+-----+
only showing top 20 rows

note: 4:
+-------+-----+
|   mots|count|
+-------+-----+
|      o| 1878|
|     do| 1616|
|      e| 1615|
|produto| 1476|
|      a| 1351|
|     de| 1315|
|       | 1135|
|    que| 1116|
|    não|  819|
|     no|  768|
|  muito|  767|
|      é|  732|
|  prazo|  722|
|  antes|  703|
|    com|  684|
|Produto|  599|
|      O|  555|
|     um|  547|
|entrega|  545|
| chegou|  534|
+-------+-----+
only showing top 20 rows

note: 5:
+-------+-----+
|   mots|count|
+-------+-----+
|      e| 5796|
|     do| 5785|
|       | 4282|
|  antes| 4227|
|produto| 4172|
|      o| 3994|
|     de| 3500|
|  muito| 3433|
|      a| 3128|
|  prazo| 3055|
|Produto| 2431|
| chegou| 2074|
|entrega| 1961|
|    bem| 1947|
|    que| 1823|
|    com| 1789|
|     no| 1771|
|    bom| 1679|
|  Muito| 1438|
|      é| 1382|
+-------+-----+
only showing top 20 rows

yo
yo
yo
yo
yo